security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    providers:
        in_memory:
            memory:
                users:
                    owner:
                        password: $2y$12$axgBcSyplhMzeg8E/M451OfpemPfBoNNUaqxKKkRgTD4ZrjgnqFm6
                        roles: 'ROLE_ADMIN'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            form_login:
                login_path: login
                check_path: login
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/account, roles: ROLE_ADMIN }
